version: '3'

networks:
  front:
    external:
      name: front

volumes:
  epflbot-data:

services:

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - EPFLBOT_TOKEN
      - EPFLBOT_ELASTICSEARCH_HOST=elasticsearch
      - EPFLBOT_INTERFACE=https://epfl.life
      - EPFLBOT_PORT=443
    networks:
      - front
      - default
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:epfl.life,www.epfl.life
      - traefik.port=443
      - traefik.docker.network=front

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    restart: unless-stopped
    volumes:
      - epflbot-data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    restart: unless-stopped
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro

  nginx:
    image: beevelop/nginx-basic-auth
    restart: unless-stopped
    links:
      - kibana:web
    environment:
      - HTPASSWD
      - FORWARD_PORT=5601
    networks:
      - front
      - default
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:admin.epfl.life
      - traefik.port=80
      - traefik.docker.network=front
